routes/admin.php
<?php

use App\Http\Controllers\Admin\PostController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\CompanyController;
use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('layouts/master');
})->name('welcome');

Route::group([
    'as' => 'users.',
    'prefix' => 'users',
], function () {
    Route::get('/', [UserController::class, 'index'])->name('index');
    Route::get('/{user}', [UserController::class, 'show'])->name('show');
    Route::delete('/{user}', [UserController::class, 'destroy'])->name('destroy');
});

Route::group([
    'as' => 'posts.',
    'prefix' => 'posts',
], function () {
    Route::get('/', [PostController::class, 'index'])->name('index');
    Route::get('/create', [PostController::class, 'create'])->name('create');
    Route::post('/store', [PostController::class, 'store'])->name('store');
    Route::post('/import-csv', [PostController::class, 'importCSV'])->name('importCSV');
});

Route::group([
    'as' => 'companies.',
    'prefix' => 'companies',
], function () {
    Route::get('/', [\App\Http\Controllers\Admin\CompanyController::class, 'index'])->name('index');
    Route::get('/create', [\App\Http\Controllers\Admin\CompanyController::class, 'create'])->name('create');
    Route::post('/save', [\App\Http\Controllers\Admin\CompanyController::class, 'save'])->name('save');
    Route::post('/store', [CompanyController::class, 'store'])->name('store');
});

routes/web.php
<?php

use App\Http\Controllers\AuthController;
use App\Http\Controllers\TestController;
use Illuminate\Support\Facades\Route;
use Laravel\Socialite\Facades\Socialite;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('layouts/master');
})->name('welcome');

Route::get('/test', [TestController::class, 'test']);

Route::get('/login', [AuthController::class, 'login'])->name('login');
Route::get('/register', [AuthController::class, 'register'])->name('register');
Route::post('/register', [AuthController::class, 'registering'])->name('registering');
Route::get('/logout', [AuthController::class, 'logout'])->name('logout');

Route::get('/auth/redirect/{provider}', function ($provider) {
    return Socialite::driver($provider)->redirect();
})->name('auth.redirect');

Route::get('/auth/callback/{provider}', [AuthController::class, 'callback'])->name('auth.callback');

app/Models/User.php
<?php

namespace App\Models;

use App\Enums\UserRoleEnum;
use Illuminate\Auth\Authenticatable;
use Illuminate\Contracts\Auth\Authenticatable as AuthAuthenticatable;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class User extends Model implements AuthAuthenticatable
{
    use HasFactory;
    use Authenticatable;

    protected $fillable = [
        'email',
        'name',
        'avatar',
    ];

    public function company() {
        return $this->belongsTo(Company::class);
    }

    public function getRoleNameAttribute() {
        return UserRoleEnum::getKeys($this->role)[0];
    }

    public function getGenderNameAttribute() {
        return ($this->gender == 0) ? 'Male' : 'Female';
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Enums\UserRoleEnum;
use App\Http\Controllers\Controller;
use App\Models\Company;
use App\Models\User;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Http\Request;
use View;

class UserController extends Controller
{
    private object $model;
    private string $table;
    private string $title;

    public function __construct()
    {
        $this->model = User::query();
        $this->table = (new User())->getTable();
        $this->title = ucwords($this->table);

        View::share('title', $this->title);
        View::share('table', $this->table);
    }

    public function index(Request $request) {
        $selectedRole = $request->get('role');
        $selectedCity = $request->get('city');
        $selectedCompany = $request->get('company');

        $query = $this->model
            ->with('company:id,name');

        if (!empty($selectedRole) && $selectedRole != 'All') {
            $query->where('role', $selectedRole);
        }
        if (!empty($selectedCity) && $selectedCity != 'All') {
            $query->where('city', $selectedCity);
        }
        if (!empty($selectedCompany) && $selectedCompany != 'All') {
            $query->where('company_id', $selectedCompany);
        }

        $data = $query->paginate();

        $cities = User::distinct()->pluck('city');
        $companies = Company::select('id', 'name')->get();
        $roles = UserRoleEnum::asArray();

        return view("admin.$this->table.index", [
            'data' => $data,
            'roles' => $roles,
            'cities' => $cities,
            'companies' => $companies,
            'selectedRole' => $selectedRole,
            'selectedCity' => $selectedCity,
            'selectedCompany' => $selectedCompany,
        ]);
    }

    public function destroy($userId) {
        User::destroy($userId);
        return redirect()->back();
    }
}

resources/views/admin/users/index.blade.php
@extends('layouts.master')

@section('content')
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <form class="form-horizontal" id="form-filter" action="">
                        <div style="gap: 20px;" class="form-group d-flex flex-row">
                            <div>
                                <label for="role">Role</label>
                                <select name="role" id="role" class="custom-select custom-select-sm mb-3 select-filter">
                                    <option selected>All</option>
                                    @foreach ($roles as $role => $value)
                                        <option value="{{ $value }}" 
                                        @if ((string)$value == $selectedRole) selected @endif
                                        >
                                            {{ $role }} 
                                        </option>
                                    @endforeach
                                </select> 
                            </div>
                            <div>
                                <label for="city">City</label>
                                <select name="city" id="city" class="custom-select custom-select-sm mb-3 select-filter">
                                    <option selected>All</option>
                                    @foreach ($cities as $city)
                                        <option value="{{ $city }}"
                                        @if ($city == $selectedCity) selected @endif
                                        >
                                            {{ $city }} 
                                        </option>
                                    @endforeach
                                </select> 
                            </div>
                            <div>
                                <label for="company">City</label>
                                <select name="company" id="company" class="custom-select custom-select-sm mb-3 select-filter">
                                    <option selected>All</option>
                                    @foreach ($companies as $company)
                                        <option value="{{ $company->id }}"
                                        @if ($company->id == $selectedCompany) selected @endif
                                        >
                                            {{ $company->name }} 
                                        </option>
                                    @endforeach
                                </select> 
                            </div>
                            
                        </div>
                    </form>
                </div>
                <div class="card-body">
                    <table class="table table-hover table-centered mb-0">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Avatar</th>
                                <th>Info</th>
                                <th>Role</th>
                                <th>Position</th>
                                <th>City</th>
                                <th>Company</th>
                                <th>Delete</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($data as $key=>$each)
                                <tr>
                                    <td>
                                        <a class="" href="{{ route("admin.$table.show", $each->id) }}">
                                            {{ $key+1 }}
                                        </a>
                                    </td>
                                    <td>
                                        <img src="{{ $each->avatar }}" width="50" class="rounded-circle">
                                    </td>
                                    <td>
                                        {{ $each->name }} <br>
                                        <a href="mailto: {{ $each->email }} ">
                                            {{ $each->email }}
                                        </a> <br>
                                        <a href="tel: {{ $each->phone }} ">
                                            {{ $each->phone }}
                                        </a> <br>
                                        {{ $each->gender_name }} <br>
                                    </td>
                                    <td>{{ $each->role_name }}</td>
                                    <td>{{ $each->position }}</td>
                                    <td>{{ $each->city }}</td>
                                    <td>{{ optional($each->company)->name }}</td>
                                    <td>
                                        <form action="{{ route("admin.$table.destroy", $each->id) }}" method="post">
                                            @csrf
                                            @method('DELETE')
                                            <Button class="btn btn-danger">Delete</Button>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                    <nav>
                        <ul class="pagination pagination-rounded mb-0">
                            {{ $data->links() }}
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('js')
    <script>
        $(document).ready(function () {
            $('.select-filter').change(function () {
                $("#form-filter").submit();
            });
        });
    </script>
@endpush