routes/admin.php
<?php

use App\Http\Controllers\Admin\PostController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\CompanyController;
use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('layouts/master');
})->name('welcome');

Route::group([
    'as' => 'users.',
    'prefix' => 'users',
], function () {
    Route::get('/', [UserController::class, 'index'])->name('index');
    Route::get('/{user}', [UserController::class, 'show'])->name('show');
    Route::delete('/{user}', [UserController::class, 'destroy'])->name('destroy');
});

Route::group([
    'as' => 'posts.',
    'prefix' => 'posts',
], function () {
    Route::get('/', [PostController::class, 'index'])->name('index');
    Route::get('/create', [PostController::class, 'create'])->name('create');
    Route::post('/store', [PostController::class, 'store'])->name('store');
    Route::post('/import-csv', [PostController::class, 'importCSV'])->name('importCSV');
});

Route::group([
    'as' => 'companies.',
    'prefix' => 'companies',
], function () {
    Route::get('/', [\App\Http\Controllers\Admin\CompanyController::class, 'index'])->name('index');
    Route::get('/create', [\App\Http\Controllers\Admin\CompanyController::class, 'create'])->name('create');
    Route::post('/save', [\App\Http\Controllers\Admin\CompanyController::class, 'save'])->name('save');
    Route::post('/store', [CompanyController::class, 'store'])->name('store');
});

routes/web.php
<?php

use App\Http\Controllers\AuthController;
use App\Http\Controllers\TestController;
use Illuminate\Support\Facades\Route;
use Laravel\Socialite\Facades\Socialite;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('layouts/master');
})->name('welcome');

Route::get('/test', [TestController::class, 'test']);

Route::get('/login', [AuthController::class, 'login'])->name('login');
Route::get('/register', [AuthController::class, 'register'])->name('register');
Route::post('/register', [AuthController::class, 'registering'])->name('registering');
Route::get('/logout', [AuthController::class, 'logout'])->name('logout');

Route::get('/auth/redirect/{provider}', function ($provider) {
    return Socialite::driver($provider)->redirect();
})->name('auth.redirect');

Route::get('/auth/callback/{provider}', [AuthController::class, 'callback'])->name('auth.callback');

app/Models/Post.php
<?php

namespace App\Models;

use App\Enums\PostCurrencySalaryEnum;
use App\Enums\PostRemotableEnum;
use App\Enums\StatusEnum;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Str;

use function PHPUnit\Framework\isNull;

class Post extends Model
{
    use HasFactory;

    protected $fillable = [
        'city',
        'company_id',
        'currency_salary',
        'district',
        'end_date',
        'is_partime',
        'is_pinned',
        'job_title',
        'max_salary',
        'min_salary',
        'number_applicants',
        'remotable',
        'requirement',
        'slug',
        'start_date',
        'status',
        'user_id'
    ];

    protected static function booted() {
        static::creating(static function ($object) {
            // $object->user_id = auth()->id();
            $object->user_id = user()->id;
            $object->status = StatusEnum::getByRole();
        });
    }

    public function language()
    {
        return $this->morphToMany(Language::class, 'object', ObjectLanguage::class, 'object_id', 'language_id');
    }

    public function company()
    {
        return $this->belongsTo(Company::class);
    }

    public function file()
    {
        return $this->hasOne(File::class);
    }

    public function getCurrencySalaryCodeAttribute(): string
    {
        return PostCurrencySalaryEnum::getKey($this->currency_salary);
    }

    public function getRemotableNameAttribute(): string
    {
        $key = PostRemotableEnum::getKey($this->remotable);
        $arr = explode('_', $key);
        $str = '';
        foreach ($arr as $each) {
            $str .= Str::title($each) . ' ';
        }

        return $str;
    }

    public function getStatusNameAttribute(): string
    {
        return StatusEnum::getKey($this->status);
    }

    public function getSalaryAttribute(): string
    {
        $val = $this->currency_salary;
        $key = PostCurrencySalaryEnum::getKey($val);
        $locale = PostCurrencySalaryEnum::getLocaleByVal($val);
        $format = new \NumberFormatter($locale, \NumberFormatter::CURRENCY);

        if(!is_null($this->min_salary)) {
            $minSalary = $format->formatCurrency($this->min_salary, $key);
        }

        if(!is_null($this->max_salary)) {
            $max_salary = $format->formatCurrency($this->max_salary, $key);
        }

        if (!empty($minSalary) && !empty($max_salary)) {
            return $minSalary . ' - ' . $max_salary;
        }

        if (!empty($minSalary)) {
            return 'From' . ' ' . $minSalary;
        }

        if (!empty($max_salary)) {
            return 'To' . ' ' . $max_salary;
        }

        return '';
    }

    public function getIsExpiredAttribute(): bool
    {
        $now = date('Y-m-d');
        if ($now >= $this->end_date && !is_null($this->end_date)) {
            return true;
        }

        return false;
    }
}

app/Http/Controllers/Applicant/HomePageController.php
<?php

namespace App\Http\Controllers\Applicant;

use App\Enums\PostRemotableEnum;
use App\Enums\StatusEnum;
use App\Http\Controllers\Controller;
use App\Http\Requests\Home\IndexRequest;
use App\Http\Requests\Home\IndexResquest;
use App\Models\Config;
use App\Models\Post;
use Illuminate\Http\Request;

class HomePageController extends Controller
{
    public function index(IndexRequest $request)
    {
        //Get Array City
        $cities = Post::pluck('city');
        $arrCity = [];

        foreach ($cities as $city) {
            if (!in_array($city, $arrCity)) {
                array_push($arrCity, $city);
            }
        }

        //Get Post
        $query = Post::with([
                'language',
                'company:id,name,logo',
            ])
            ->where('status', StatusEnum::ADMIN_APPROVE)
            ->orderByDesc('is_pinned')
            ->orderByDesc('id');

        //Filter City
        $filterCities = $request->get('cities', []);
        if (!empty($filterCities)) {
            $query->whereIn('city', $filterCities);
        }

        //Filter Salary
        $configs = Config::where('is_public', false)->get();
        $arrConfig = [];
        foreach ($configs as $config) {
            $arrConfig[$config->key] = $config->value;
        }
        $minSalary = $request->get('min_salary', $arrConfig['filter_min_salary']);
        $maxSalary = $request->get('max_salary', $arrConfig['filter_max_salary']);
        if($request->has('min_salary')) {
            $query->where('min_salary', '>=', $minSalary);
        }
        if($request->has('max_salary')) {
            $query->where('max_salary', '<=', $maxSalary);
        }

        //Filter Partime
        $filterPartime = $request->get('partime');
        if(!empty($filterPartime)) {
            $query->where('is_partime', 1);
        }

        //Filter Remotable
        $filterRemotable = $request->get('remotable');
        if (!empty($filterRemotable)) {
            $query->where('remotable', $filterRemotable);
        }

        $posts = $query->paginate()->withQueryString();

        //Add more attribute
        foreach ($posts as $post) {
            $post->salary_name = $post->salary;
            $post->expired = $post->is_expired;
        }

        //Get Array Remotable
        $filterPostRemotable = PostRemotableEnum::getArrWithLowerKey();

        return view('applicant.index', [
            'posts' => $posts,
            'arrCity' => $arrCity,
            'filterCities' => $filterCities,
            'minSalary' => $minSalary,
            'maxSalary' => $maxSalary,
            'filterPostRemotable' => $filterPostRemotable,
            'filterPartime' => $filterPartime,
            'filterRemotable' => $filterRemotable,
        ]);
    }

    public function show($postId)
    {
        $post = Post::with('file')
                ->where('status', StatusEnum::ADMIN_APPROVE)
                ->findOrFail($postId);

        return view('applicant.show', [
            'post' => $post,
        ]);
    }
}

resources/views/applicant/index.blade.php
@extends('layout_page.master')

@section('content')
    <h2 class="section-title">Find what you need</h2>
    <div class="row">
        <!-- SIDEBAR -->
        @include('layout_page.sidebar')
        <!-- END SIDEBAR -->

        <div class="col-md-9">
            <div class="row">
                @foreach ($posts as $post)
                    <x-post :post="$post" />
                @endforeach
            </div>
            <ul class="pagination pagination-info" style="float: right;">
                {{ $posts->links() }}
            </ul>
        </div>
    </div>
@endsection

@push('js')
    <script type="text/javascript">
        $(document).ready(function() {

            var slider2 = document.getElementById('sliderRefine');

            const minSalary = parseInt($("#input-min-salary").val());
            const maxSalary = parseInt($("#input-max-salary").val());

            noUiSlider.create(slider2, {
                start: [{{ $minSalary }}, {{ $maxSalary }}],
                connect: true,
                step: 50,
                range: {
                    'min': [200],
                    'max': [2500]
                }
            });

            let val;
            slider2.noUiSlider.on('update', function(values, handle) {
                val = Math.round(values[handle])
                if (handle) {
                    $("#span-max-salary").text(val);
                    $("#input-max-salary").val(val);
                } else {
                    $("#span-min-salary").text(val);
                    $("#input-min-salary").val(val);
                }
            });
        });
    </script>
@endpush

resources/views/applicant/show.blade.php
@extends('layout_page.master')

@section('content')
    <div class="row">
        <div class="col-md-4 col-sm-6">

            <div class="tab-content">
                <div class="card card-pricing">
                    <div class="card-content">
                        <ul>
                            <li>{{ $post->remotable_name }}</li>
                            @if ($post->is_partime)
                                <li>
                                    <i class="material-icons text-success">
                                        check
                                    </i>
                                    Part-time
                                </li>
                            @else
                                <li>
                                    <i class="material-icons text-danger">
                                        close
                                    </i>
                                    Part-time
                                </li>
                            @endif
                            @isset($post->number_applicants)
                                <li><i class="material-icons text-success">check</i> 
                                    Number applicants: {{ $post->number_applicants }}
                                </li>
                            @endisset
                            @if(!empty($post->start_date) && !empty($post->end_date))
                                <li>
                                    Date: {{ $post->start_date }} - {{ $post->end_date }}
                                </li>
                            @endif
                        </ul>
                        
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-6 col-sm-6">
            <h2 class="title"> 
                {{ $post->job_title }}
            </h2>
            <h3 class="main-price">
                {{ $post->salary }}
            </h3>
            <h4>
                <a href="@">
                    {{ $post->company->name }}
                </a>
            </h4>
            <h4>
                {{ $post->district }} - {{ $post->city }}
            </h4>

            @if (!empty($post->requirement))
            <div id="acordeon">
                <div class="panel-group" id="accordion">
                    <div class="panel panel-border panel-default">
                        <div class="panel-heading" role="tab" id="headingOne">
                            <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne"
                                aria-expanded="true" aria-controls="collapseOne">
                                <h4 class="panel-title">
                                    Requirement
                                    <i class="material-icons">keyboard_arrow_down</i>
                                </h4>
                            </a>
                        </div>
                        <div id="collapseOne" class="panel-collapse collapse in">
                            <div class="panel-body">
                                <p>{{ $post->requirement }}</p>
                            </div>
                        </div>
                    </div>

                </div>
            </div><!--  end acordeon -->
            @endif

            @isset($post->file)
                <div class="row text-right">
                    <a class="btn btn-rose btn-round" href="{{ $post->file->link }}" target="_blank">
                        Open file &nbsp;
                        <i class="fa fa-file"></i>
                    </a>
                </div>
            @endisset
        </div>
    </div>
@endsection